server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   
  type-aliases-package: com.song.springcloud.entity                      
  mapper-locations:                                    
  - classpath:mybatis/mapper/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    
    driver-class-name: org.gjt.mm.mysql.Driver     
    url: jdbc:mysql://10.32.173.250:3306/uc?useUnicode=true&characterEncoding=utf-8&useSSL=true      
    username: uc                                  
    password: uc                               
    dbcp2:                                          
      min-idle: 5                                 
      initial-size: 5                            
      max-total: 5                                 
      max-wait-millis: 200     
  application: 
      name: order-service-provider
      
eureka: 
  instance: 
    instance-id: order-service-provider-8001
    prefer-ip-address: true # 访问路径可以显示 IP
  client: 
    service-url: 
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/    #注册中心访问地址    
